#!/usr/env/bin bash
# vim: set filetype=sh :
# shellcheck disable=SC1091,SC2154

export KEYTIMEOUT=30
export EDITOR="nvim"
export VISUAL="nvim"
export TABSIZE=2

export SSH_TERM="xterm-256color"
export PROJECTS_DIR="${HOME}/Desktop/tutoriais_e_cursos"

ZSH_HIGHLIGHT_STYLES[comment]='fg=240'
ZSH_HIGHLIGHT_STYLES[default]='fg=251'
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=red,bold'

export OLLAMA_HOST=192.168.0.109:11434
export OLLAMA_TIMEOUT_MS=10000
export OLLAMA_LOAD_TIMEOUT='10m'
export OLLAMA_KEEP_ALIVE='10m'
export LOCAL_MODEL="qwen3.6:35b-a3b-mlx-bf16"
export MODEL="${LOCAL_MODEL}"

export KOKORO_VOICES_PT='pf_dora,af_heart,if_sara,ff_siwis,ef_dora,pm_santa'
export KOKORO_VOICES_EN='bf_emma,af_heart,af_bella,bf_isabella,ff_siwis,if_sara'

export FZF_DEFAULT_COMMAND='fd --type f --strip-cwd-prefix --hidden --follow --exclude .git'
export FZF_DEFAULT_OPTS=${FZF_DEFAULT_OPTS:-}"
  --color=fg:#eae8ff,fg+:#6bccff,bg:#000010,bg+:#151520
  --color=hl:#6bccff,hl+:#ffffff,info:#6bccff,marker:#6bccff
  --color=prompt:#eeeeff,spinner:#6bccff,pointer:#6bccff,header:#6bccff
  --color=gutter:#151520,border:#151520,separator:#151520,scrollbar:#6bccff
  --color=label:#6bccff,query:#ccccee
  --border=\"rounded\" --border-label=\"tmux\" --border-label-pos=\"0\" 
  --preview-window=\"border-rounded\"
  --padding=\"0\" --margin=\"0\" --prompt=\"> \" --marker=\">\"
  --pointer=\"◆\" --separator=\"─\" --scrollbar=\"│\" --layout=\"reverse\""

export FZF_FILE_LIMIT=1000
export FZF_FILE_DEPTH=8

export FZF_RG_LIMIT=100
export FZF_RG_DEPTH=8
export FZF_RG_MAX_FILESIZE=1M

# BE SURE TO FIX THE ENV VARIABLES
# brew install libpq --build-from-source
# brew install mysql-client
# brew install openssl
# brew install curl

# PKG_CONFIG_PATH acumulado corretamente
export PKG_CONFIG_PATH="/opt/homebrew/opt/curl/lib/pkgconfig:$PKG_CONFIG_PATH"
export PKG_CONFIG_PATH="/opt/homebrew/opt/sqlite/lib/pkgconfig:$PKG_CONFIG_PATH"

# LDFLAGS (links de bibliotecas nativas)
export LDFLAGS="-L/opt/homebrew/lib -L/opt/homebrew/opt/openssl/lib -L/opt/homebrew/opt/openssl@3/lib -L/opt/homebrew/opt/curl/lib -L/opt/homebrew/opt/mysql-client/lib -L/opt/homebrew/opt/libpq/lib -L/opt/homebrew/opt/sqlite/lib"

# CPPFLAGS (cabeçalhos de compilação)
export CPPFLAGS="-I/opt/homebrew/include -I/opt/homebrew/opt/openssl/include -I/opt/homebrew/opt/openssl@3/include -I/opt/homebrew/opt/curl/include -I/opt/homebrew/opt/mysql-client/include -I/opt/homebrew/opt/libpq/include -I/opt/homebrew/opt/sqlite/include"

# bat command
export BAT_STYLE="header"
export BAT_THEME="ansi"

PATH="/opt/homebrew/opt/curl/bin:/opt/homebrew/opt/mysql-client/bin:/opt/homebrew/opt/libpq/bin:${PATH}"

if [ "$(uname -s)" = "Linux" ]; then
  PATH="/home/linuxbrew/.linuxbrew/bin:${PATH}"
  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
elif [ "$(uname -s)" = "Darwin" ]; then
  PATH="/opt/homebrew/opt/sqlite/bin:${PATH}"
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

export PYENV_ROOT="${HOME}/.pyenv"
PATH="${PYENV_ROOT}/bin:${PYENV_ROOT}/shims:${PATH}"
[[ -z "$PYENV_ROOT" ]] || eval "$(pyenv init -)"

. "$HOME/.local/bin/env"
[ -f ~/.fzf.zsh ] && . "${HOME}/.fzf.zsh"

if [[ "$(uname -s)" == "Linux" ]]; then
  [[ -r "/home/linuxbrew/.linuxbrew/etc/profile.d/bash_completion.sh" ]] \
    && . "/home/linuxbrew/.linuxbrew/etc/profile.d/bash_completion.sh"
fi

if [[ "$(uname -s)" == "Darwin" ]]; then
  [[ -r "/opt/homebrew/etc/profile.d/bash_completion.sh" ]] \
    && . "/opt/homebrew/etc/profile.d/bash_completion.sh"
fi

if [[ "$(command -v just)" && -f "Justfile" ]]; then
  eval "$(just --completions zsh)"
fi

if [[ "$(command -v codex)" ]]; then
  eval "$(codex completion zsh)"
fi

if [[ "$(command -v docker)" && -f "${HOME}/.docker/completions/_docker" ]]; then
  eval "$(docker completion zsh)"
fi

if [[ "$(command -v gh)" ]]; then
  eval "$(gh completion -s zsh)"
fi

# bun completions
[ -s "/Users/luizotavio/.oh-my-zsh/completions/_bun" ] && source "/Users/luizotavio/.oh-my-zsh/completions/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
PATH="$BUN_INSTALL/bin:$PATH"

# Added by Antigravity
PATH="$HOME/.antigravity/antigravity/bin:$PATH"

# pnpm
export PNPM_HOME="/Users/luizotavio/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

path=("${HOME}/dotfiles/scripts" "${HOME}/.local/bin" "${path[@]}")
typeset -gU path

export PATH
