#!/bin/sh
# vim: set filetype=sh :

# Reset
RESET='\033[0m'

# Cores normais
BLACK='\033[0;30m'
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
MAGENTA='\033[0;35m'
CYAN='\033[0;36m'
WHITE='\033[0;37m'

# Cores em negrito (bold ou bright)
BRIGHT_BLACK='\033[1;30m'
BRIGHT_RED='\033[1;31m'
BRIGHT_GREEN='\033[1;32m'
BRIGHT_YELLOW='\033[1;33m'
BRIGHT_BLUE='\033[1;34m'
BRIGHT_MAGENTA='\033[1;35m'
BRIGHT_CYAN='\033[1;36m'
BRIGHT_WHITE='\033[1;37m'

# Funções para printar mensagens coloridas de forma legível
log() {
  printf "${CYAN}%s${RESET}\n" "$1"
}

loginfo() {
  log "🔵 $1"
}

logsuccess() {
  printf "🟢 ${GREEN}%s${RESET}\n" "$1"
}

logerror() {
  printf "🔴 ${RED}%s${RESET}\n" "$1"
}


function dtouch() {
  mkdir -p "$(dirname "$1")"
  touch "$1"
}

function componentTs() {
  # code -r src/components/"$1"/index.tsx src/components/"$1"/"$1".tsx src/components/"$1"/"$1".module.css
  mkdir -p src/components/"$1"
  zed -a src/components/"$1"/index.tsx
  zed -a src/components/"$1"/"$1".spec.tsx
  zed -a src/components/"$1"/"$1".test.tsx
  zed -a src/components/"$1"/"$1".stories.tsx
  zed -a src/components/"$1"/"$1".module.css
}

function componentJs() {
  code -r src/components/"$1"/styles.js src/components/"$1"/index.jsx src/components/"$1"/stories.jsx src/components/"$1"/"$1".spec.jsx
}

function aula_c() {
  [ -z "$1" ] && echo "Empty Param, send a class name" && return
  ffmpeg -i \
    "/Users/luizotavio/Desktop/$1.mp4" -vf "scale=1920:1080" -sws_flags lanczos \
    -c:v libx264 -crf 23 -preset slow -c:a aac -b:a 160k \
    "/Users/luizotavio/Desktop/$1-c.mp4"
}

function memoryUsage() {
  ps -A -o rss,comm | grep -E "$1" | grep -v grep | awk '{ sum += $1 } END { printf "%.2f MB\n", sum / 1024 }'
}

function deletePythonCache() {
    echo "Limpando diretórios de cache e build..."

    deactivate
    find . -type d \( -name "__pycache__" -o -name ".pytest_cache" -o -name ".tox" -o -name "*.egg-info" -o -name "build" -o -name "dist" \) -exec rm -r {} \;
    find . -type f \( -name "*.pyc" -o -name "*.pyo" \) -delete

    echo "Limpeza concluída com sucesso!"
}

function cleanNeovimLogs() {
    echo "🧼 Iniciando limpeza de logs e cache do Neovim..."

    [[ -d ~/.local/state/nvim ]] && rm ~/.local/state/nvim/*.log
    [[ -d ~/.cache/nvim ]] && {
        rm ~/.cache/nvim/*.log
        rm -r ~/.cache/nvim/shada
        rm -r ~/.cache/nvim/sessions
    }
    echo "✅ Neovim limpo com sucesso!"
}

function iterm() {
    cwd=$(pwd)
    open -a iterm $cwd
}

restart_terminal() {
    . ~/.zshrc
    tmux respawn-window -k
}

function show_fg_colors() {
  echo
  echo "🎨 Foreground colors (0–255):"
  for i in {0..255}; do
    local label=""
    case $i in
      0) label="black" ;;
      1) label="red" ;;
      2) label="green" ;;
      3) label="yellow" ;;
      4) label="blue" ;;
      5) label="magenta" ;;
      6) label="cyan" ;;
      7) label="white" ;;
      8) label="brightblack (gray)" ;;
      9) label="brightred" ;;
      10) label="brightgreen" ;;
      11) label="brightyellow" ;;
      12) label="brightblue" ;;
      13) label="brightmagenta" ;;
      14) label="brightcyan" ;;
      15) label="brightwhite" ;;
    esac
    print -P "%F{$i}█  %3d  %-22s%f" $i "$label"
  done
}


function show_bg_colors() {
  echo
  echo "🧱 Background colors (0–255):"
  for i in {0..255}; do
    local label=""
    case $i in
      0) label="black" ;;
      1) label="red" ;;
      2) label="green" ;;
      3) label="yellow" ;;
      4) label="blue" ;;
      5) label="magenta" ;;
      6) label="cyan" ;;
      7) label="white" ;;
      8) label="brightblack (gray)" ;;
      9) label="brightred" ;;
      10) label="brightgreen" ;;
      11) label="brightyellow" ;;
      12) label="brightblue" ;;
      13) label="brightmagenta" ;;
      14) label="brightcyan" ;;
      15) label="brightwhite" ;;
    esac
    print -P "%K{$i}  %-3d %s  %k" $i "$label"
  done
}

function gitconfig() {
  set -e

  log "Your name:"
  read NAME

  log "Your e-mail:"
  read EMAIL

  log

  # Initialize git
  log "Command: git init"
  git init

  # Configurar o nome do usuário"
  log "Command: git config user.name \"${NAME}\""
  git config user.name "${NAME}"

  # Configurar o e-mail do usuário"
  log "Command: git config user.email \"${EMAIL}\""
  git config user.email "${EMAIL}"

  # Muda o nome do branch para main"
  log "Command: git branch -m main"
  git branch -m main

  # Garantir que o Git converta CRLF para LF apenas ao commitar (ótimo para projetos multiplataforma)"
  log "Command: git config core.autocrlf input"
  git config core.autocrlf input

  # Forçar o Git a usar LF como fim de linha sempre"
  log "Command: git config core.eol lf"
  git config core.eol lf

  # Verificar as configurações aplicadas"
  log "Command: git config --list --local"
  # git config --list --local
  #
  # Adicionando o repositório"
  # log "git add ."
  # log "git commit -m \"initial\""
  # log "git remote add origin LINK-REPO"
  # log "git push origin main -u  "
}

function tmux_respawn_all() {
  for pane in $(tmux list-panes -a -F '#D'); do 
    tmux respawn-pane -k -t $pane; 
  done
}

