#!/usr/bin/env bash
# vim: set filetype=sh :

# Local .env
# shellcheck disable=SC1091
[[ -f ~/.env ]] && source "${HOME}/.env"

if [[ -z "$SPLASH_SHOWN" ]]; then
  export SPLASH_SHOWN=1
  printf "%b\n\n" "$(< "${HOME}/dotfiles/zsh/splash.txt")"
  # printf "%b\n\n" "$(cat "${HOME}/dotfiles/zsh/splash.txt")"
fi


ZSH_CONFIG_DIR="$HOME/dotfiles/zsh/config"

CONFIG_CONFIG_FILE="${ZSH_CONFIG_DIR}/config"
FUNCTIONS_CONFIG_FILE="${ZSH_CONFIG_DIR}/functions"
EXPORTS_CONFIG_FILE="${ZSH_CONFIG_DIR}/exports"
ALIASES_CONFIG_FILE="${ZSH_CONFIG_DIR}/aliases"
KEYBINDS_CONFIG_FILE="${ZSH_CONFIG_DIR}/keybinds"

ZSH_CONFIG_FILES=(
  "$CONFIG_CONFIG_FILE"
  "$FUNCTIONS_CONFIG_FILE" 
  "$EXPORTS_CONFIG_FILE"
  "$ALIASES_CONFIG_FILE" 
  "$KEYBINDS_CONFIG_FILE"
)

for f in "${ZSH_CONFIG_FILES[@]}"; do
  if test -f "$f"; then
    # shellcheck disable=SC1090
    source "$f"
  else
    printf "%s" "404: $f not found.\n"
  fi
done

