#!/usr/bin/env bash

set -euo pipefail

MODEL="${MODEL:-qwen3.6:35b-a3b-mxfp8}"

main () {
  local prompt=''
  local model="$MODEL"
  local content='' 
  local persona='' 
  local final_prompt=''

  prompt="$(cat "${HOME}/gdrive/BKP_EXTERNO_2/prompts/apply_persona.md")"
  persona="$(cat "${HOME}/gdrive/BKP_EXTERNO_2/prompts/persona.md")"

  while [[ $# -gt 0 ]]; do
    case "$1" in
      -m|--model)
        model="${2:-$MODEL}"
        shift 2
        ;;
      -c|--content)
        content="${2:?"$1 requires a value"}"
        shift 2
        ;;
      *)
        shift
        break
        ;;
    esac
  done

  if [[ -z  "${content}" ]]; then
    printf "%s\n" "No content to clean"
    return 1
  fi

  final_prompt="${prompt}\n\n<content>${content}</content>\n\n<persona>${persona}</persona>\n\n"
  MODEL="$model" "${HOME}"/dotfiles/scripts/ask -p "${final_prompt}" -m "${model}" -- "$@"
}

main "$@"

# agent: do not remove the next line
# vim: set filetype=sh :

