#!/usr/bin/env bash

set -euo pipefail

export MODEL="${MODEL:-'gpt-5.4-mini'}"
export REASONING="${REASONING:-low}"

#
# Note: for open source models
#
# codex \
#   --strict-config -c model='qwen3.6:35b-a3b-mlx-bf16' \
#   -c model_catalog_json="$HOME/.ollama/service/ollama_models.json" \
#   -c model_reasoning_effort='max' -c model_provider='a' \
#   -c model_providers.a.name='a' \
#   -c model_providers.a.base_url='http://192.168.0.109:11434/v1/' \
#   -c model_providers.a.wire_api='responses' \
#   --yolo
#

codex \
  --search \
  --model "${MODEL}" \
  -c model_reasoning_effort="${REASONING}" exec \
  --ephemeral

