#!/usr/bin/env bash

set -euo pipefail

os="$(uname -s)"
audio="${audio:-1}"
alert="${alert:-0}"

if [[ "${audio}" == 1 ]]; then
  if ! command -v ffplay >/dev/null; then
    echo "ffplay not found"
    exit 1
  fi

  (
    for _ in {1..3}; do
      ffplay -nodisp -loglevel quiet -autoexit -volume 100 "${HOME}"/dotfiles/sounds/notify.oga >/dev/null & sleep 1
    done
  ) &
fi

if [[ "${os}" == "Darwin" ]]; then
  now="$(date '+%Y-%m-%d %H:%M')"
  msg="${msg:-You should write a message}"

  if [[ "${alert}" == 1 ]]; then
    osascript \
      -e "display dialog \"${msg}\n\n${now}\"¬" \
      -e 'with title "Alert"¬' \
      -e 'with icon stop¬' \
      -e 'buttons {"OK"}¬' \
      -e 'default button "OK"' >/dev/null
  fi
fi
