#!/usr/bin/env python3.14
# Copyright (c) 2026 Luiz Otávio Miranda

import argparse
import string
import textwrap
from secrets import SystemRandom

MINIMUM_SIZE = 8


class Args(argparse.Namespace):
  size: int
  punctuation: bool
  lower: bool
  upper: bool
  digits: bool


def validate_min(value: str) -> int:
  try:
    number = int(value)
  except ValueError as e:
    msg = "Invalid integer value"
    raise argparse.ArgumentTypeError(msg) from e

  if number < MINIMUM_SIZE:
    msg = f"The minimum size must be {MINIMUM_SIZE}"
    raise argparse.ArgumentTypeError(msg)

  return number


def generate_string(args: Args) -> str:
  values: set[str] = set()
  sr = SystemRandom()

  if args.lower:
    values = values.union(set(string.ascii_lowercase))

  if args.upper:
    values = values.union(set(string.ascii_uppercase))

  if args.digits:
    values = values.union(set(string.digits))

  if args.punctuation:
    values = values.union(set(string.punctuation))

  values.difference_update("'\"`\\")

  return "".join(sr.choices(list(values), k=args.size))


def parse_args() -> Args:
  parser = argparse.ArgumentParser(
    prog="password_generator",
    description=textwrap.dedent(
      "This is a simple password or random values generator."
    ),
    formatter_class=argparse.ArgumentDefaultsHelpFormatter,
  )

  parser.add_argument(
    "-s", "--size", default=24, type=validate_min, help="Number of characters"
  )
  parser.add_argument(
    "--punctuation",
    help="Include punctuation values",
    default=True,
    action=argparse.BooleanOptionalAction,
  )
  parser.add_argument(
    "--lower",
    help="Include lower case letters",
    default=True,
    action=argparse.BooleanOptionalAction,
  )
  parser.add_argument(
    "--upper",
    help="Include upper case letters",
    default=True,
    action=argparse.BooleanOptionalAction,
  )
  parser.add_argument(
    "--digits",
    help="Include digits (0-9)",
    default=True,
    action=argparse.BooleanOptionalAction,
  )

  args = parser.parse_args(namespace=Args())
  if not any((args.punctuation, args.lower, args.upper, args.digits)):
    parser.error("enable at least one character group")
  return args


def main() -> None:
  args = parse_args()
  print(generate_string(args))


if __name__ == "__main__":
  main()
