#!/usr/bin/env bash

set -euo pipefail

find "${PROJECTS_DIR}/" -maxdepth 1 -mindepth 1 -type d   \
  -exec bash -lc '
  set -euo pipefail
  cd {} || exit 1
  git status --porcelain >/dev/null 2>&1
  echo "{}"
  git pull --all --prune --ff-only
  prline
  ' \;

