#!/usr/bin/env zsh

fc -W

"$HOME"/dotfiles/scripts/zsh_history_sync.py
"$HOME"/.tmux/plugins/tmux-resurrect/scripts/save.sh

sleep 2

(
  rm -rf "$HOME"/.local/share/tmux/resurrect/*.*
  rm -rf "$HOME"/.local/share/tmux/resurrect/**
  rm -rf "$HOME"/.local/share/tmux/resurrect/.*
) > /dev/null 2>&1 || true

sleep 2

"$HOME"/.tmux/plugins/tmux-resurrect/scripts/save.sh

ls -lah "$HOME"/.local/share/tmux/resurrect

echo
prline

# m4128
rsync -havz --progress --stats "$HOME"/.local/share/tmux/resurrect/ \
  m4128:~/.local/share/tmux/resurrect/ --delete

rsync -havz --progress --stats "$HOME"/Desktop/tutoriais_e_cursos/ \
  m4128:~/Desktop/tutoriais_e_cursos --delete

echo
prline

# fedoraair
rsync -havz --progress --stats "$HOME"/.local/share/tmux/resurrect/ \
  fedoraair:~/.local/share/tmux/resurrect/ --delete

rsync -havz --progress --stats "$HOME"/Desktop/tutoriais_e_cursos/ \
  fedoraair:~/Desktop/tutoriais_e_cursos --delete

echo
prline
