#!/usr/bin/env zsh

set -euo pipefail

fc -W

"$HOME"/dotfiles/scripts/zsh_history_sync.py

"$HOME"/.tmux/plugins/tmux-resurrect/scripts/save.sh 

(
  rm -rf "$HOME"/.local/share/tmux/resurrect/{*.*,.*,**} 
) > /dev/null 2>&1 || true

"$HOME"/.tmux/plugins/tmux-resurrect/scripts/save.sh 

ls -lah "$HOME"/.local/share/tmux/resurrect

rsync -havz --progress --stats "$HOME"/.local/share/tmux/resurrect/ \
  m4128:~/.local/share/tmux/resurrect/ --delete

rsync -havz --progress --stats "$HOME"/Desktop/tutoriais_e_cursos/ \
  m4128:~/Desktop/tutoriais_e_cursos --delete
