#!/usr/bin/env bash

set -euo pipefail

tmuxns() {
  if [[ -z "${1:-}" ]]; then
    echo "Please, inform the name for the session."
    return 1
  fi

  session_name="$1"
  shift

  if [[ -z "${PROJECTS_DIR}" ]]; then
    echo "Could not find PROJECTS_DIR env variable"
    return 1
  fi

  session_dir="${PROJECTS_DIR}/${session_name}"
  mkdir -p "${session_dir}"

  tmux has-session -t "${session_name}" 2>/dev/null || tmux new-session -d -s "${session_name}" -c "${session_dir}" -n "code"

  for arg in "$@"; do
    tmux new-window -t "${session_name}" -n "${arg}" -c "${session_dir}"
  done
}

tmuxns "${@}"

