#!/usr/bin/env bash

set -Eeuo pipefail

report_error() {
  local status="$1" command="$2"
  printf 'tmuxnw: ERROR: command failed (exit %s): %s\n' "$status" "$command" >&2
  exit "$status"
}
trap 'report_error "$?" "$BASH_COMMAND"' ERR

WINDOW_NAME="tmp"

if (($# > 0)); then
  WINDOW_NAME="${1:-new}"
  shift
fi

SESSION_NAME="$(tmux display-message -p "#{session_name}")"
WINDIR="${WINDIR:-$(pwd)}"
tmux neww -t "$SESSION_NAME" -c "$WINDIR" -n "$WINDOW_NAME" -a "$@"
