#!/usr/bin/env bash

set -euo pipefail

trap 'echo "Error on line $LINENO"' ERR

tmux_make_sessions() {
  projects_dir=${1:-$PROJECTS_DIR}

  [[ -d "${projects_dir}" ]] || logerror "'${projects_dir}' is not a directory"

  [[ "$(pgrep tmux)" ]] && (echo "Kill tmux current server, then run this script." ; exit 1)


  echo "This may take a while. Please wait..."

  rm -Rf ~/.local/share/tmux/resurrect/*.*

  home_session="HOME"
  home_path="${HOME}"
  other_windows=("term")

  tmux new -s "${home_session}" -d -n code -c "${home_path}"

  for how in "${other_windows[@]}"; do
    tmux neww -k -S -a -t "${home_session}" -d -n "${how}" -c "${home_path}"
  done

  dotfiles_session="dotfiles"
  dotfiles_path="${home_path}/dotfiles"

  tmux new -s "${dotfiles_session}" -d -n code -c "${dotfiles_path}"

  for dow in "${other_windows[@]}"; do
    tmux neww -k -S -a -t "${dotfiles_session}" -d -n "${dow}" -c "${dotfiles_path}"
  done

  find "${projects_dir}/" -mindepth 1 -maxdepth 1 -type d -print0 | while IFS= read -r -d '' dir; do
    dirname=$(basename "${dir}")

    session_name="${dirname//./_}"
    first_window_name="code"

    tmux new -s "${session_name}" -d -n "${first_window_name}" -c "${dir}"

    for ow in "${other_windows[@]}"; do
      tmux neww -d -k -S -a -n "${ow}" -t "${session_name}" -c "${dir}"
    done
  done

  ~/.tmux/plugins/tmux-resurrect/scripts/save.sh

  echo "Done. Now run: 'tmux a'"
}

tmux_make_sessions "${@}"
