#!/usr/bin/env bash

set -euo pipefail

WINDOW_NAME="tmp"

if (($# > 0)); then
  WINDOW_NAME="${1:-new}"
  shift
fi

SESSION_NAME="$(tmux display-message -p "#{session_name}")"
WINDIR="${WINDIR:-$(pwd)}"
tmux neww -t "$SESSION_NAME" -c "$WINDIR" -n "$WINDOW_NAME" -a "$@"
