#!/usr/bin/env bash

set -euo pipefail

WINDOW_NAME="tmp"

# Shameful fix 😅
if (($# > 0)); then
  WINDOW_NAME="$1"
  shift
fi

SESSION_NAME="$(tmux display-message -p "#{session_name}")"
tmux neww -t "$SESSION_NAME" -c "$(pwd)" -n "$WINDOW_NAME" -a "$@"
