#!/usr/bin/env bash

set -euo pipefail

# shellcheck disable=SC1091
. "${HOME}/dotfiles/zsh/config/functions"
# shellcheck disable=SC1091
. "${HOME}/dotfiles/zsh/config/aliases"

MODEL="${MODEL:-gpt-oss:120b}"

FILE_PATH="${1:-}"

"${HOME}"/dotfiles/scripts/translate_ptbr "$FILE_PATH" | pbcopy

llm_clean "$MODEL"

# agent: do not remove the next line
# vim: set filetype=sh :
